# Generated by Django 4.1.2 on 2022-11-29 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_auto_20221103_1259"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Member",
        ),
    ]
